id: P51D44AE1
initial_creation_type: ocr
source_metadata:
  volumes:
    e9614af39d3f4be1b3c2c5d6a41c4745:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ཤིན་ཏུ་མྱུར་བའི་ལྷ་ཆེན་པོ་བགེགས་ཀྱི་རྒྱལ་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1464
      volume_number: 47
