id: D94DA546D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:31:39+00:00'
last_modified: '2022-05-30T07:30:40.727806+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '8727':
      image_group_id: I1PD95892
      title: ཤིན་ཏུ་མྱུར་བའི་ལྷ་ཆེན་པོ་བགེགས་ཀྱི་རྒྱལ་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1464
      order: 47
      base_file: 8727.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
